{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "cb62f665_3551d6b3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 9
      },
      "lineNbr": 13,
      "author": {
        "id": 1015244
      },
      "writtenOn": "2021-04-14T12:16:36Z",
      "side": 1,
      "message": "Did you update the commit message by mistake?\n\nThis is the wrong issue id:\nIssue 14028: Global ref-db should rollback the ref-update upon failure on Zookeeper",
      "range": {
        "startLine": 13,
        "startChar": 0,
        "endLine": 13,
        "endChar": 16
      },
      "revId": "9dd8dca7606edb3528366b3238027c9929364a94",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}